services:
  back:
    image: evaberry/docker
    environment:
      - CURRENT_ENVIRONMENT=development
    expose:
      - "5000"
    # volumes:
    #   - ./logs/my-messages.log:/app/my-messages.log

  front:
    image: mon-front
    ports:
      - "8080:80"
    environment:
      - WS_BACK_URL=http://back:5000